--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/luca28pet/TimeRanks
build-by-default: true
branches:
- master
projects:
  TimeRanks:
    path: ""
    libs:
      - src: poggit/libasynql/libasynql
        version: ^4.0.0
...
