name: TimeRanks
main: TimeRanks\Main
version: 1.0.0beta
api: [1.1.0]

load: POSTWORLD
author: luca28pet
description: Add easy ranks to your server
website: https://github.com/luca28pet/TimeRanks
commands:
 timeranks:
  description: The main command
  usage: "/timeranks <get|set>"
  aliases: [tr, ranks, tranks]
  permission: timeranks.command
permissions:
 advancedkits.command:
  description: "Allows to use the main command"
  default: true
