name: TimeRanks
main: luca28pet\timeranks\TimeRanks
version: 3.0.0
api: 4.0.0
load: POSTWORLD
author: luca28pet
description: Add time-based ranks to your server
website: https://github.com/luca28pet/TimeRanks
permissions:
  timeranks.command.self:
    description: "Allows to execute /tr command and check play time"
    default: "true"
  timeranks.command.others:
    description: "Allows to show the minutes another player has played"
    default: "op"
  timeranks.exempt:
    description: "Exempt a player from rankup"
    default: "op"

