name: TimeRanks
main: TimeRanks\TimeRanks
version: 2.0.0
api: [2.0.0 , 3.0.0-ALPHA1 , 3.0.0-ALPHA2 , 3.0.0-ALPHA3]

load: POSTWORLD
author: luca28pet
description: Add easy ranks to your server
website: https://github.com/luca28pet/TimeRanks
permissions:
 timeranks.command:
  description: "Allows to use the main command"
  default: true
 timeranks.exempt:
  description: "Exempt rankup"
  default: op
